### ISSUE TITLE
Needs to be updated

### ISSUE THREAD

**Issue by lorrinevil** [demourak/goemerchant-woocommerce-plugin#22]
I've called the company twice to see when we would get an update after the massive woocommerce upgrade in April.  We are attempting to integrate our desktop quickbooks with online and the payment info isn't being stored in the correct area to sync properly (paypal is perfect) when will this be updated? I'm talking to some other merchant solutions right now-  huge problem. 
From my quickbooks integration developer : Mainly...no transaction id or payment info is being stored in Woocommerce.

**Comment by demourak** [comment]
Hello,
Would you provide more details on the issue you're experiencing?
WooCommerce identifies each transaction with an order ID. This is the same number that the goEmerchant gatway uses as the Order ID (unless there is an order ID prefix set, in which case goEmerchant will store an ID of [prefix] + order_id.

The plugin is currently undergoing an update for the latest WooCommerce, which will be live soon.

Thanks much!

**Comment by lorrinevil** [comment]
Hi KevinPeter (quickbooks sync Developer) is included on this email - I've passed your specific question along to him - thank you for your response - I felt like the calls I've made might not have been passed along to you - appreciate hearing from you. Hoping the upgrade will include being able to auto refund from our invoices like we can do with paypal - As soon as I get the specific issue he or I will let you know - I'm already having to pay for upgraded special plugins we use - I don't feel we should have to pay him to develop a work around for our merchant company :-) - His quickbooks sync is the best I've seen and it will be good for both of you to be able to say "compatible with" 
Thank you in advance!Lorri
===========================
Thank You
Lorri Nevil. Executive Team Leader  #14521434Origami Owl Independent Designer903-880-2824
Visit my site for the latest Jewelry! http://LorrisCharms.OrigamiOwl.comJoin my VIP Group for special pampering! https://www.facebook.com/groups/vipcharmclub/
Please like my Facebook Page! http://www.facebook.com/LorrisLivingLockets



On Friday, August 11, 2017, 8:53:55 AM CDT, Kevin DeMoura <notifications@github.com> wrote:


Hello,
Would you provide more details on the issue you're experiencing?
WooCommerce identifies each transaction with an order ID. This is the same number that the goEmerchant gatway uses as the Order ID (unless there is an order ID prefix set, in which case goEmerchant will store an ID of [prefix] + order_id.

The plugin is currently undergoing an update for the latest WooCommerce, which will be live soon.

Thanks much!

**Comment by lorrinevil** [comment]
Kevin,

Great to meet you - Lorri, thanks for the introduction.

It seems the core issue here is that the transaction ID for the payment isn’t being stored in WooCommerce…which is one of the values our plugin uses to determine whether the payment was made - and being able to push it over to QuickBooks Online.

Do ya’ll have any plans to be storing the transaction ID in WooCommerce in future versions? If not…it will probably be most efficient for us to look into building in custom compatibility with GoeMerchant.

Thanks,

Peter

         <http://myworks.design/> 			 	
Peter L <mailto:sales@myworks.design> CEO
MyWorks Design <http://myworks.design/>
#Software   #Web Design   #Consulting <http://myworks.design/>
 <http://facebook.com/myworksdesign>  <http://m.me/myworksdesign>  <http://twitter.com/myworksdesign>  <http://slack.myworks.design/>

**Comment by demourak** [comment]
Hi Peter,

When an order is created, it can be accessed in the WooCommerce dashboard by clicking on its associated order ID. This order ID is stored by WooCommerce in the Wordpress database. 

Can you clarify exactly how you are trying to retrieve and use the WooCommerce order ID and why this has been unsuccessful so far?
